AmimirMVC/Controllers/EstadoController.cs
using AmimirMVC.Models;
using AmimirMVC.ServiceReferenceAmimir;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AmimirMVC.Controllers
{
    public class EstadoController : Controller
    {

        Service1Client client = new Service1Client();

        public ActionResult Index()
        {
            var lista = client.estadoLista();

            return View(lista);
        }

        public ActionResult Edit(int ID)
        {
            EstadoCLS tEstadoCLS = new EstadoCLS();

            var datos = client.estadoDatos(ID);

            tEstadoCLS.ID = datos.ID;
            tEstadoCLS.nombre = datos.nombre;

            return View(tEstadoCLS);
        }

        [HttpPost]
        public ActionResult Edit(EstadoCLS tEstadoCLS)
        {
            client.estadoEditar(tEstadoCLS.ID, tEstadoCLS.nombre);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int ID)
        {
            EstadoCLS tEstadoCLS = new EstadoCLS();

            var datos = client.estadoDatos(ID);

            tEstadoCLS.ID = datos.ID;
            tEstadoCLS.nombre = datos.nombre;

            return View(tEstadoCLS);
        }

        [HttpPost]
        public ActionResult Delete(EstadoCLS tEstadoCLS)
        {
            client.estadoBorrar(tEstadoCLS.ID);

            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(EstadoCLS oEstadoCLS)
        {
            client.estadoGuardar(oEstadoCLS.nombre);

            return RedirectToAction("Index");
        }
    }
}

AmimirMVC/Views/Estado/Create.cshtml
@model AmimirMVC.Models.EstadoCLS

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EstadoCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmimirMVC/Views/Estado/Delete.cshtml
@model AmimirMVC.Models.EstadoCLS

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EstadoCLS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AmimirMVC/Views/Estado/Edit.cshtml
@model AmimirMVC.Models.EstadoCLS

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EstadoCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AmimirMVC/Views/Estado/Index.cshtml
@model IEnumerable<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear estado", "Create", "Estado", null, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>